"""Compatibility facade for PM++ potential corrections.

New correction implementations live under :mod:`pmpp.corrections`. This module is
kept so existing scripts/tests that import ``pmpp.potential_correction`` continue
to work.
"""

from .corrections import (
    CombinedPotentialCorrection,
    MeshCNNPotentialCorrection,
    MeshResidualPotentialCorrection,
    NeuralSplineFourierFilter,
    PGDPotentialCorrection,
    PMWindowCompensationCorrection,
    RadialPotentialCorrection,
    HighKSofteningCorrection,
    TrainablePGDPotentialCorrection,
    TrainablePMWindowCompensationCorrection,
    add_potential_correction_cotangents,
    apply_potential_correction,
    build_correction_optimizer,
    evaluate_mesh_potential_residual,
    evaluate_mesh_source_residual,
    evaluate_pm_window_compensation,
    evaluate_potential_transfer,
    evaluate_high_k_softening,
    evaluate_pgd_bandpass,
    evaluate_pgd_potential_transfer,
    evaluate_radial_potential_transfer,
    force_green_kernel,
    force_uses_interlacing,
    init_mesh_cnn_potential_correction,
    init_pm_window_compensation_correction,
    init_potential_correction,
    init_pgd_potential_correction,
    init_radial_potential_correction,
    init_high_k_softening_correction,
    init_trainable_pgd_potential_correction,
    init_trainable_pm_window_compensation_correction,
    pgd_parameters,
    pgd_alpha,
    pm_window_parameters,
    resolve_sigma8,
    sample_potential_transfer,
    zero_potential_correction_cotangent,
)

__all__ = [
    "CombinedPotentialCorrection",
    "MeshCNNPotentialCorrection",
    "MeshResidualPotentialCorrection",
    "NeuralSplineFourierFilter",
    "PGDPotentialCorrection",
    "PMWindowCompensationCorrection",
    "RadialPotentialCorrection",
    "HighKSofteningCorrection",
    "TrainablePGDPotentialCorrection",
    "TrainablePMWindowCompensationCorrection",
    "add_potential_correction_cotangents",
    "apply_potential_correction",
    "build_correction_optimizer",
    "evaluate_mesh_potential_residual",
    "evaluate_mesh_source_residual",
    "evaluate_pm_window_compensation",
    "evaluate_potential_transfer",
    "evaluate_high_k_softening",
    "evaluate_pgd_bandpass",
    "evaluate_pgd_potential_transfer",
    "evaluate_radial_potential_transfer",
    "force_green_kernel",
    "force_uses_interlacing",
    "init_mesh_cnn_potential_correction",
    "init_pm_window_compensation_correction",
    "init_potential_correction",
    "init_pgd_potential_correction",
    "init_radial_potential_correction",
    "init_high_k_softening_correction",
    "init_trainable_pgd_potential_correction",
    "init_trainable_pm_window_compensation_correction",
    "pgd_parameters",
    "pgd_alpha",
    "pm_window_parameters",
    "resolve_sigma8",
    "sample_potential_transfer",
    "zero_potential_correction_cotangent",
]
