"""Potential correction models and dispatch helpers."""

from .combined import CombinedPotentialCorrection
from .common import build_correction_optimizer, resolve_sigma8
from .core import (
    add_potential_correction_cotangents,
    apply_potential_correction,
    evaluate_mesh_potential_residual,
    evaluate_mesh_source_residual,
    evaluate_potential_transfer,
    evaluate_radial_potential_transfer,
    force_green_kernel,
    force_gradient_kernel,
    force_uses_interlacing,
    init_potential_correction,
    sample_potential_transfer,
    zero_potential_correction_cotangent,
)
from .mesh_cnn import (
    MeshCNNPotentialCorrection,
    MeshResidualPotentialCorrection,
    init_mesh_cnn_potential_correction,
)
from .pgd import (
    PGDPotentialCorrection,
    TrainablePGDPotentialCorrection,
    evaluate_pgd_bandpass,
    evaluate_pgd_potential_transfer,
    init_pgd_potential_correction,
    init_trainable_pgd_potential_correction,
    pgd_parameters,
    pgd_alpha,
)
from .radial import (
    NeuralSplineFourierFilter,
    RadialPotentialCorrection,
    init_radial_potential_correction,
)
from .window import (
    PMWindowCompensationCorrection,
    TrainablePMWindowCompensationCorrection,
    evaluate_pm_window_compensation,
    init_pm_window_compensation_correction,
    init_trainable_pm_window_compensation_correction,
    pm_window_parameters,
)
from .softening import (
    HighKSofteningCorrection,
    evaluate_high_k_softening,
    init_high_k_softening_correction,
)
from .nbody import (
    BoundedPhaseSpaceCorrection,
    NBodyCorrection,
    add_nbody_correction_cotangents,
    apply_local_pair_correction,
    apply_phase_space_correction,
    evaluate_phase_space_residual,
    has_phase_space_correction,
    init_bounded_phase_space_correction,
    local_pair_correction,
    long_range_correction,
    phase_space_correction,
    phase_space_is_invertible,
    prepare_phase_space_context,
    zero_nbody_correction_cotangent,
)
from .local_pair import (
    LocalPairCorrection,
    LocalPairPhaseContext,
    RadialLocalPairPotential,
    evaluate_local_pair_potential,
    init_local_pair_correction,
    init_local_pair_phase_space_correction,
    local_pair_phase_space_head,
    prepare_local_pair_phase_context,
)

__all__ = [
    "CombinedPotentialCorrection",
    "BoundedPhaseSpaceCorrection",
    "NBodyCorrection",
    "LocalPairCorrection",
    "LocalPairPhaseContext",
    "RadialLocalPairPotential",
    "MeshCNNPotentialCorrection",
    "MeshResidualPotentialCorrection",
    "NeuralSplineFourierFilter",
    "PGDPotentialCorrection",
    "PMWindowCompensationCorrection",
    "RadialPotentialCorrection",
    "HighKSofteningCorrection",
    "TrainablePGDPotentialCorrection",
    "TrainablePMWindowCompensationCorrection",
    "add_potential_correction_cotangents",
    "add_nbody_correction_cotangents",
    "apply_local_pair_correction",
    "apply_phase_space_correction",
    "apply_potential_correction",
    "build_correction_optimizer",
    "evaluate_mesh_potential_residual",
    "evaluate_mesh_source_residual",
    "evaluate_local_pair_potential",
    "evaluate_pm_window_compensation",
    "evaluate_potential_transfer",
    "evaluate_high_k_softening",
    "evaluate_pgd_bandpass",
    "evaluate_pgd_potential_transfer",
    "evaluate_radial_potential_transfer",
    "evaluate_phase_space_residual",
    "force_green_kernel",
    "force_gradient_kernel",
    "force_uses_interlacing",
    "has_phase_space_correction",
    "init_bounded_phase_space_correction",
    "init_local_pair_correction",
    "init_local_pair_phase_space_correction",
    "init_mesh_cnn_potential_correction",
    "init_pm_window_compensation_correction",
    "init_potential_correction",
    "init_pgd_potential_correction",
    "init_radial_potential_correction",
    "init_high_k_softening_correction",
    "init_trainable_pgd_potential_correction",
    "init_trainable_pm_window_compensation_correction",
    "local_pair_correction",
    "local_pair_phase_space_head",
    "long_range_correction",
    "phase_space_correction",
    "phase_space_is_invertible",
    "prepare_phase_space_context",
    "prepare_local_pair_phase_context",
    "pgd_parameters",
    "pgd_alpha",
    "pm_window_parameters",
    "resolve_sigma8",
    "sample_potential_transfer",
    "zero_potential_correction_cotangent",
    "zero_nbody_correction_cotangent",
]
