title: PM++
author: rouzib
execute:
  execute_notebooks: "off"
repository:
  url: https://github.com/rouzib/PMpp
  path_to_book: docs/source
  branch: master
  provider: github
html:
  use_repository_button: true
  use_issues_button: true
sphinx:
  config:
    html_theme: pydata_sphinx_theme
    autodoc_mock_imports:
      - h5py
      - haiku
      - optax
    autosummary_generate: true
    napoleon_google_docstring: false
    napoleon_numpy_docstring: true
    autodoc_typehints: description
    myst_enable_extensions:
      - dollarmath
      - amsmath
      - colon_fence
  extra_extensions:
    - sphinx.ext.autodoc
    - sphinx.ext.autosummary
    - sphinx.ext.napoleon
    - sphinx.ext.mathjax
    - sphinx.ext.viewcode
    - sphinx.ext.intersphinx
    - sphinx_copybutton
    - sphinx_design
    - sphinxcontrib.mermaid
